[build]
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.100.2"
    HUGO_THEME = "repo"

[context.production]
    command = 'hugo --theme=theme --baseUrl="https://kirklin.cn/"'
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = 'hugo --theme=theme --baseUrl="https://kirklin.cn/"'

[context.deploy-preview]
    command = 'hugo --theme=theme --baseUrl="https://kirklin.cn/"'

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
            # Relative path to source directory in case you use Hugo's "--s" option
            srcdir = "public"
